version: '3.8'
services:
  server:
    build:
      context: ./server
    ports:
      - "5001:5000"
  
  proxy:
    build:
      context: ./proxy
    ports:
      - "5000:5000"
    depends_on:
      - server

  client1:
    build:
      context: ./client
    ports:
      - "8081:80"

  client2:
    build:
      context: ./client
    ports:
      - "8082:80"

  client3:
    build:
      context: ./client
    ports:
      - "8083:80"
